#!/bin/sh
# mkdir ./results/for_honk/original2maono_zscore_scaled_batch1
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/down --save_dir ./results/for_honk/original2maono_zscore_scaled_batch1/down --name original2maono_mfcc_zscore_scaled --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/up --save_dir ./results/for_honk/original2maono_zscore_scaled_batch1/up --name original2maono_mfcc_zscore_scaled --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/yes --save_dir ./results/for_honk/original2maono_zscore_scaled_batch1/yes --name original2maono_mfcc_zscore_scaled --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/no --save_dir ./results/for_honk/original2maono_zscore_scaled_batch1/no --name original2maono_mfcc_zscore_scaled --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/left --save_dir ./results/for_honk/original2maono_zscore_scaled_batch1/left --name original2maono_mfcc_zscore_scaled --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/right --save_dir ./results/for_honk/original2maono_zscore_scaled_batch1/right --name original2maono_mfcc_zscore_scaled --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/stop --save_dir ./results/for_honk/original2maono_zscore_scaled_batch1/stop --name original2maono_mfcc_zscore_scaled --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/go --save_dir ./results/for_honk/original2maono_zscore_scaled_batch1/go --name original2maono_mfcc_zscore_scaled --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/on --save_dir ./results/for_honk/original2maono_zscore_scaled_batch1/on --name original2maono_mfcc_zscore_scaled --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/off --save_dir ./results/for_honk/original2maono_zscore_scaled_batch1/off --name original2maono_mfcc_zscore_scaled --model cycle_gan


# mkdir ./results/for_honk/original2maono_zscore_scaled_batch8
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/down --save_dir ./results/for_honk/original2maono_zscore_scaled_batch8/down --name original2maono_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/up --save_dir ./results/for_honk/original2maono_zscore_scaled_batch8/up --name original2maono_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/yes --save_dir ./results/for_honk/original2maono_zscore_scaled_batch8/yes --name original2maono_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/no --save_dir ./results/for_honk/original2maono_zscore_scaled_batch8/no --name original2maono_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/left --save_dir ./results/for_honk/original2maono_zscore_scaled_batch8/left --name original2maono_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/right --save_dir ./results/for_honk/original2maono_zscore_scaled_batch8/right --name original2maono_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/stop --save_dir ./results/for_honk/original2maono_zscore_scaled_batch8/stop --name original2maono_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/go --save_dir ./results/for_honk/original2maono_zscore_scaled_batch8/go --name original2maono_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/on --save_dir ./results/for_honk/original2maono_zscore_scaled_batch8/on --name original2maono_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/off --save_dir ./results/for_honk/original2maono_zscore_scaled_batch8/off --name original2maono_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 16
# mkdir ./results/for_honk/original2maono_zscore_scaled_batch16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/down --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16/down --name original2maono_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/up --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16/up --name original2maono_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/yes --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16/yes --name original2maono_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/no --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16/no --name original2maono_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/left --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16/left --name original2maono_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/right --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16/right --name original2maono_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/stop --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16/stop --name original2maono_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/go --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16/go --name original2maono_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/on --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16/on --name original2maono_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/off --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16/off --name original2maono_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16

# mkdir ./results/for_honk/original2maono_zscore_scaled_batch16_instance_norm
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/down --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16_instance_norm/down --name original2maono_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/up --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16_instance_norm/up --name original2maono_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/yes --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16_instance_norm/yes --name original2maono_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/no --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16_instance_norm/no --name original2maono_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/left --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16_instance_norm/left --name original2maono_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/right --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16_instance_norm/right --name original2maono_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/stop --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16_instance_norm/stop --name original2maono_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/go --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16_instance_norm/go --name original2maono_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/on --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16_instance_norm/on --name original2maono_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/off --save_dir ./results/for_honk/original2maono_zscore_scaled_batch16_instance_norm/off --name original2maono_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# 
# # mkdir ./results/for_honk/original2maono_zscore_scaled_batch32
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/down --save_dir ./results/for_honk/original2maono_zscore_scaled_batch32/down --name original2maono_mfcc_zscore_scaled_batch32 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/up --save_dir ./results/for_honk/original2maono_zscore_scaled_batch32/up --name original2maono_mfcc_zscore_scaled_batch32 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/yes --save_dir ./results/for_honk/original2maono_zscore_scaled_batch32/yes --name original2maono_mfcc_zscore_scaled_batch32 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/no --save_dir ./results/for_honk/original2maono_zscore_scaled_batch32/no --name original2maono_mfcc_zscore_scaled_batch32 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/left --save_dir ./results/for_honk/original2maono_zscore_scaled_batch32/left --name original2maono_mfcc_zscore_scaled_batch32 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/right --save_dir ./results/for_honk/original2maono_zscore_scaled_batch32/right --name original2maono_mfcc_zscore_scaled_batch32 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/stop --save_dir ./results/for_honk/original2maono_zscore_scaled_batch32/stop --name original2maono_mfcc_zscore_scaled_batch32 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/go --save_dir ./results/for_honk/original2maono_zscore_scaled_batch32/go --name original2maono_mfcc_zscore_scaled_batch32 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/on --save_dir ./results/for_honk/original2maono_zscore_scaled_batch32/on --name original2maono_mfcc_zscore_scaled_batch32 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/maono_zscore_scaled/off --save_dir ./results/for_honk/original2maono_zscore_scaled_batch32/off --name original2maono_mfcc_zscore_scaled_batch32 --model cycle_gan --norm batch --batch_size 16

# mkdir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch1
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch1/down --name original2ATR_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch1/up --name original2ATR_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch1/yes --name original2ATR_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch1/no --name original2ATR_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch1/left --name original2ATR_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch1/right --name original2ATR_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch1/stop --name original2ATR_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch1/go --name original2ATR_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch1/on --name original2ATR_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch1/off --name original2ATR_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# mkdir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch4
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch4/down --name original2ATR_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch4/up --name original2ATR_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch4/yes --name original2ATR_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch4/no --name original2ATR_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch4/left --name original2ATR_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch4/right --name original2ATR_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch4/stop --name original2ATR_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch4/go --name original2ATR_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch4/on --name original2ATR_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch4/off --name original2ATR_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# mkdir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch8/down --name original2ATR_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch8/up --name original2ATR_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch8/yes --name original2ATR_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch8/no --name original2ATR_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch8/left --name original2ATR_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch8/right --name original2ATR_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch8/stop --name original2ATR_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch8/go --name original2ATR_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch8/on --name original2ATR_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch8/off --name original2ATR_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8


# mkdir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16/down --name original2ATR_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16/up --name original2ATR_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16/yes --name original2ATR_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16/no --name original2ATR_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16/left --name original2ATR_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16/right --name original2ATR_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16/stop --name original2ATR_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16/go --name original2ATR_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16/on --name original2ATR_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16/off --name original2ATR_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16

# mkdir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16_instance_norm
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16_instance_norm/down --name original2ATR_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16_instance_norm/up --name original2ATR_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16_instance_norm/yes --name original2ATR_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16_instance_norm/no --name original2ATR_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16_instance_norm/left --name original2ATR_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16_instance_norm/right --name original2ATR_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16_instance_norm/stop --name original2ATR_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16_instance_norm/go --name original2ATR_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16_instance_norm/on --name original2ATR_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2ATR_mfcc_zscore_scaled_batch16_instance_norm/off --name original2ATR_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16


# mkdir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch1
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch1/down --name original2clipon_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch1/up --name original2clipon_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch1/yes --name original2clipon_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch1/no --name original2clipon_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch1/left --name original2clipon_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch1/right --name original2clipon_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch1/stop --name original2clipon_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch1/go --name original2clipon_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch1/on --name original2clipon_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch1/off --name original2clipon_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# mkdir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch4
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch4/down --name original2clipon_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch4/up --name original2clipon_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch4/yes --name original2clipon_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch4/no --name original2clipon_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch4/left --name original2clipon_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch4/right --name original2clipon_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch4/stop --name original2clipon_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch4/go --name original2clipon_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch4/on --name original2clipon_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch4/off --name original2clipon_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# mkdir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch8/down --name original2clipon_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch8/up --name original2clipon_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch8/yes --name original2clipon_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch8/no --name original2clipon_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch8/left --name original2clipon_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch8/right --name original2clipon_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch8/stop --name original2clipon_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch8/go --name original2clipon_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch8/on --name original2clipon_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch8/off --name original2clipon_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# 
# 
# mkdir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16/down --name original2clipon_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16/up --name original2clipon_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16/yes --name original2clipon_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16/no --name original2clipon_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16/left --name original2clipon_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16/right --name original2clipon_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16/stop --name original2clipon_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16/go --name original2clipon_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16/on --name original2clipon_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16/off --name original2clipon_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# mkdir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16_instance_norm
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16_instance_norm/down --name original2clipon_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16_instance_norm/up --name original2clipon_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16_instance_norm/yes --name original2clipon_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16_instance_norm/no --name original2clipon_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16_instance_norm/left --name original2clipon_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16_instance_norm/right --name original2clipon_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16_instance_norm/stop --name original2clipon_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16_instance_norm/go --name original2clipon_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16_instance_norm/on --name original2clipon_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2clipon_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2clipon_mfcc_zscore_scaled_batch16_instance_norm/off --name original2clipon_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16

# mkdir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch1
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch1/down --name original2USB_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch1/up --name original2USB_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch1/yes --name original2USB_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch1/no --name original2USB_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch1/left --name original2USB_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch1/right --name original2USB_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch1/stop --name original2USB_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch1/go --name original2USB_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch1/on --name original2USB_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch1/off --name original2USB_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# mkdir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch4
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch4/down --name original2USB_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch4/up --name original2USB_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch4/yes --name original2USB_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch4/no --name original2USB_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch4/left --name original2USB_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch4/right --name original2USB_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch4/stop --name original2USB_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch4/go --name original2USB_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch4/on --name original2USB_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch4/off --name original2USB_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# mkdir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch8/down --name original2USB_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch8/up --name original2USB_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch8/yes --name original2USB_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch8/no --name original2USB_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch8/left --name original2USB_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch8/right --name original2USB_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch8/stop --name original2USB_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch8/go --name original2USB_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch8/on --name original2USB_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch8/off --name original2USB_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# 
# 
# mkdir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16/down --name original2USB_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16/up --name original2USB_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16/yes --name original2USB_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16/no --name original2USB_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16/left --name original2USB_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16/right --name original2USB_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16/stop --name original2USB_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16/go --name original2USB_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16/on --name original2USB_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16/off --name original2USB_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# mkdir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16_instance_norm
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16_instance_norm/down --name original2USB_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16_instance_norm/up --name original2USB_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16_instance_norm/yes --name original2USB_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16_instance_norm/no --name original2USB_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16_instance_norm/left --name original2USB_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16_instance_norm/right --name original2USB_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16_instance_norm/stop --name original2USB_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16_instance_norm/go --name original2USB_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16_instance_norm/on --name original2USB_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USB_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2USB_mfcc_zscore_scaled_batch16_instance_norm/off --name original2USB_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16


# mkdir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch1
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch1/down --name original2USBplug_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch1/up --name original2USBplug_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch1/yes --name original2USBplug_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch1/no --name original2USBplug_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch1/left --name original2USBplug_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch1/right --name original2USBplug_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch1/stop --name original2USBplug_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch1/go --name original2USBplug_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch1/on --name original2USBplug_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch1/off --name original2USBplug_mfcc_zscore_scaled_batch1 --model cycle_gan --norm batch --batch_size 8
# mkdir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch4
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch4/down --name original2USBplug_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch4/up --name original2USBplug_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch4/yes --name original2USBplug_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch4/no --name original2USBplug_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch4/left --name original2USBplug_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch4/right --name original2USBplug_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch4/stop --name original2USBplug_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch4/go --name original2USBplug_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch4/on --name original2USBplug_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch4/off --name original2USBplug_mfcc_zscore_scaled_batch4 --model cycle_gan --norm batch --batch_size 4
# mkdir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch8/down --name original2USBplug_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch8/up --name original2USBplug_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch8/yes --name original2USBplug_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch8/no --name original2USBplug_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch8/left --name original2USBplug_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch8/right --name original2USBplug_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch8/stop --name original2USBplug_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch8/go --name original2USBplug_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch8/on --name original2USBplug_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch8/off --name original2USBplug_mfcc_zscore_scaled_batch8 --model cycle_gan --norm batch --batch_size 8
# 
# 
# mkdir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16/down --name original2USBplug_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16/up --name original2USBplug_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16/yes --name original2USBplug_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16/no --name original2USBplug_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16/left --name original2USBplug_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16/right --name original2USBplug_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16/stop --name original2USBplug_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16/go --name original2USBplug_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16/on --name original2USBplug_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16/off --name original2USBplug_mfcc_zscore_scaled_batch16 --model cycle_gan --norm batch --batch_size 16
# mkdir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16_instance_norm
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/down --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16_instance_norm/down --name original2USBplug_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/up --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16_instance_norm/up --name original2USBplug_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/yes --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16_instance_norm/yes --name original2USBplug_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/no --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16_instance_norm/no --name original2USBplug_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/left --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16_instance_norm/left --name original2USBplug_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/right --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16_instance_norm/right --name original2USBplug_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/stop --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16_instance_norm/stop --name original2USBplug_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/go --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16_instance_norm/go --name original2USBplug_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/on --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16_instance_norm/on --name original2USBplug_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16
# python test_wj_save4speech.py --dataroot ./datasets/original2USBplug_mfcc_zscore_scaled_honk_eval/off --save_dir ./results/for_honk/original2USBplug_mfcc_zscore_scaled_batch16_instance_norm/off --name original2USBplug_mfcc_zscore_scaled_batch16_instance_norm --model cycle_gan --batch_size 16

# mkdir ./results/for_honk/original2ATR_minmax_batch1
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_minmax_honk_eval/down --save_dir ./results/for_honk/original2ATR_minmax_batch1/down --name Original2ATR_minmax --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_minmax_honk_eval/up --save_dir ./results/for_honk/original2ATR_minmax_batch1/up --name Original2ATR_minmax --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_minmax_honk_eval/yes --save_dir ./results/for_honk/original2ATR_minmax_batch1/yes --name Original2ATR_minmax --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_minmax_honk_eval/no --save_dir ./results/for_honk/original2ATR_minmax_batch1/no --name Original2ATR_minmax --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_minmax_honk_eval/left --save_dir ./results/for_honk/original2ATR_minmax_batch1/left --name Original2ATR_minmax --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_minmax_honk_eval/right --save_dir ./results/for_honk/original2ATR_minmax_batch1/right --name Original2ATR_minmax --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_minmax_honk_eval/stop --save_dir ./results/for_honk/original2ATR_minmax_batch1/stop --name Original2ATR_minmax --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_minmax_honk_eval/go --save_dir ./results/for_honk/original2ATR_minmax_batch1/go --name Original2ATR_minmax --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_minmax_honk_eval/on --save_dir ./results/for_honk/original2ATR_minmax_batch1/on --name Original2ATR_minmax --model cycle_gan
# python test_wj_save4speech.py --dataroot ./datasets/original2ATR_minmax_honk_eval/off --save_dir ./results/for_honk/original2ATR_minmax_batch1/off --name Original2ATR_minmax --model cycle_gan

# mkdir ./results/for_honk/deepspeech_spec_original2maono
# python test_wj_save4speech.py --dataroot ./datasets/deepspeech_original2maono/deepspeech_eval --save_dir ./results/for_honk/deepspeech_spec_original2maono --name deepspeech_spec_original2maono --model cycle_gan
# mkdir ./results/for_honk/deepspeech_spec_original2maono_batch2
# python test_wj_save4speech.py --dataroot ./datasets/deepspeech_original2maono/deepspeech_eval --save_dir ./results/for_honk/deepspeech_spec_original2maono_batch2 --name deepspeech_spec_original2maono_batch2_instance_norm --model cycle_gan
# mkdir ./results/for_honk/deepspeech_spec_original2maono_batch8
# python test_wj_save4speech.py --dataroot ./datasets/deepspeech_original2maono/deepspeech_eval --save_dir ./results/for_honk/deepspeech_spec_original2maono_batch8 --name deepspeech_spec_original2maono_batch8_instance_norm --model cycle_gan
# mkdir ./results/for_honk/deepspeech_spec_ATR2USBplug
# python test_wj_save4speech.py --dataroot ./datasets/deepspeech_ATR2USBplug/deepspeech_eval --save_dir ./results/for_honk/deepspeech_spec_ATR2USBplug --name deepspeech_spec_ATR2USBplug --model cycle_gan --gpu_ids 1
mkdir ./results/for_honk/deepspeech_original2maono_extended
python test_wj_save4speech.py --dataroot ./datasets/deepspeech_original2maono/deepspeech_eval --save_dir ./results/for_honk/deepspeech_original2maono_extended --name deepspeech_original2maono_extended --model cycle_gan --gpu_ids 1 --batch_size 4

# mkdir ./results/for_honk/deepspeech_spec_original2clipon
# python test_wj_save4speech.py --dataroot ./datasets/deepspeech_original2clipon/deepspeech_eval --save_dir ./results/for_honk/deepspeech_spec_original2clipon --name deepspeech_spec_original2clipon --model cycle_gan
# mkdir ./results/for_honk/deepspeech_spec_original2ATR
# python test_wj_save4speech.py --dataroot ./datasets/deepspeech_original2ATR/deepspeech_eval --save_dir ./results/for_honk/deepspeech_spec_original2ATR --name deepspeech_spec_original2ATR --model cycle_gan
# mkdir ./results/for_honk/deepspeech_spec_original2USB
# python test_wj_save4speech.py --dataroot ./datasets/deepspeech_original2USB/deepspeech_eval --save_dir ./results/for_honk/deepspeech_spec_original2USB --name deepspeech_spec_original2USB --model cycle_gan
# mkdir ./results/for_honk/deepspeech_spec_original2USBplug
# python test_wj_save4speech.py --dataroot ./datasets/deepspeech_original2USBplug/deepspeech_eval --save_dir ./results/for_honk/deepspeech_spec_original2USBplug --name deepspeech_spec_original2USBplug --model cycle_gan